### PR TITLE
Restructuring repository to allow use as a submodule

### PR DESCRIPTION
**Pull request by preflightsiren**
I've moved the content out of the modules folder and into the root.

This lets puppet autoload the module as part of the path (inline with how: https://github.com/puppetlabs/puppetlabs-dism works)

### CODE REVIEW

**Comment by drusellers** [comment]
+1 for this

**Comment by simondean** [comment]
Hi Sebastian.  Thanks for the raising the issue.  Sorry for the delay in looking at this.  It wasn't quite straight forward as the module needed to be in a sub-directory for the acceptance tests (the acceptance tests call puppet apply and puppet apply insists on modules being sub-directories of the modulepath).  I've reworked the acceptance tests to use an NTFS junction point so that they work with the module in the root of the repo.  I've just pushed the change to github.  Let me know if this fixes things for you

**Comment by preflightsiren** [comment]
can't you just add --modulepath to the puppet executable to tell it where to find your module?
or set the environment variable?

**Comment by simondean** [comment]
I do use the --modulepath argument but unfortunately puppet will only load modules from the child directories of the module path and it won't let you point the module path directly at a single module. So you have to nest a module under another directory to get it loading via a module path. 

Have a look at the features/support/env.rb and features/step_definitions/manifest_steps.rb files for the acceptance tests code that handles the puppet apply.

**Pull request closed without merging**
